# **Basics of Numpy**  

### **NUMPY**

> NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

> An array is a collection of homogeneous data-types that are stored in contiguous memory locations.

Create a Python List as follows:

In [ ]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


## **What is Numpy?**

A numpy array is similar to a list. It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy: 

In [ ]:
# import numpy library

import numpy as np

In [ ]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [ ]:
#x = np.arange(100)
x = np.array([4,56,7,3,5,2,34,7,3,11,45,22])
x

array([ 4, 56,  7,  3,  5,  2, 34,  7,  3, 11, 45, 22])

In [ ]:
x[:5] 

array([ 4, 56,  7,  3,  5])

In [ ]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the Data-type of the array’s elements. In this case a 64-bit integer: 


In [ ]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [ ]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Check the type of array

type(b), b.dtype

(numpy.ndarray, dtype('float64'))

In [ ]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [ ]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [ ]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Slicing

Like lists, we can slice the numpy array, and we can select the elements from 1 to 3 and assign it to a new numpy array <code>d</code> as follows:

In [ ]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [ ]:
listL = [100,   1,   2, 300, 400]
listL[3:5] = 4,7
listL

[100, 1, 2, 4, 7]

In [ ]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

## **Assign Value with List**

Similarly, we can use a list to select a specific index. The list ' select ' contains several values:

In [ ]:
# Create the index list

select = [0, 2, 3]
c

array([100,   1,   2, 300, 400])

In [ ]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300])

In [ ]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

<h2 id="lin">Linspace</h2>

 A useful function for plotting mathematical functions is "linespace".   Linespace returns evenly spaced numbers over a specified interval. We specify the starting point of the sequence and the ending point of the sequence. The parameter "num" indicates the Number of samples to generate, in this case 5:

In [ ]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=100)

array([-2.        , -1.95959596, -1.91919192, -1.87878788, -1.83838384,
       -1.7979798 , -1.75757576, -1.71717172, -1.67676768, -1.63636364,
       -1.5959596 , -1.55555556, -1.51515152, -1.47474747, -1.43434343,
       -1.39393939, -1.35353535, -1.31313131, -1.27272727, -1.23232323,
       -1.19191919, -1.15151515, -1.11111111, -1.07070707, -1.03030303,
       -0.98989899, -0.94949495, -0.90909091, -0.86868687, -0.82828283,
       -0.78787879, -0.74747475, -0.70707071, -0.66666667, -0.62626263,
       -0.58585859, -0.54545455, -0.50505051, -0.46464646, -0.42424242,
       -0.38383838, -0.34343434, -0.3030303 , -0.26262626, -0.22222222,
       -0.18181818, -0.14141414, -0.1010101 , -0.06060606, -0.02020202,
        0.02020202,  0.06060606,  0.1010101 ,  0.14141414,  0.18181818,
        0.22222222,  0.26262626,  0.3030303 ,  0.34343434,  0.38383838,
        0.42424242,  0.46464646,  0.50505051,  0.54545455,  0.58585859,
        0.62626263,  0.66666667,  0.70707071,  0.74747475,  0.78

If we change the parameter <code>num</code> to 9, we get 9 evenly spaced numbers over the interval from -2 to 2: 

In [ ]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

We can use the function line space to generate 100 evenly spaced samples from the interval 0 to 2π: 

In [ ]:
# Makeup a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)

________________________________________________

### **Sorting in Numpy**

In [ ]:
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

In [ ]:
np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

In [ ]:

np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

### **Where in Numpy**



In [ ]:
# a is an array of integers.
a = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
  
print(a)
  
print ('Indices of elements <4')
  
b = np.where(a<4)

print(b,'\n')

print("Elements which are <4")
a[b] = 4
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indices of elements <4
(array([0, 0, 0]), array([0, 1, 2])) 

Elements which are <4
[[4 4 4]
 [4 5 6]
 [7 8 9]]


## **2D Elements in Numpy**

Consider the list <code>a</code>, the list contains three nested lists **each of equal size**. 

In [ ]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

We can cast the list to a Numpy Array as follow

In [ ]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions referred to as the rank. 

In [ ]:
# Show the numpy array dimensions

A.ndim

Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.

In [ ]:
# Show the numpy array shape

A.shape

The total number of elements in the array is given by the attribute <code>size</code>.

In [ ]:
# Show the numpy array size

A.size

<hr>

<h2 id="access">Accessing different elements of a Numpy Array</h2>

We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoEg.png" width="500" />

We can access the 2nd-row 3rd column as shown in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png" width="400" />

 We simply use the square brackets and the indices corresponding to the element we would like:

In [ ]:
# Access the element on the second row and third column

A[1, 2]

 We can also use the following notation to obtain the elements: 

In [ ]:
# Access the element on the second row and third column

A[1][2]

 Consider the elements shown in the following figure 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFF.png" width="400" />

We can access the element as follows 

In [ ]:
# Access the element on the first row and first column

A[0][0]

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png" width="400" />

 This can be done with the following syntax 

In [ ]:
# Access the element on the first row and first and second columns

A[0][0:2]

Similarly, we can obtain the first two rows of the 3rd column as follows:

In [ ]:
# Access the element on the first and second rows and third column

A[0:2, 2]

Corresponding to the following figure: 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png" width="400" />

<hr>

<h2 id="op">Basic Operations</h2>

We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

The numpy array is given by <code>X</code> and <code>Y</code>

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

In [ ]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

 We can add the numpy arrays as follows.

In [ ]:
# Add X and Y

Z = X + Y
Z

## **Numpy - Other Attributes**

In [ ]:
a = np.array([0, 1, 2, 3, 4])

In [ ]:
# Get the size of numpy array

a.size

4

In [ ]:
# Get the number of dimensions of numpy array

a.ndim

1

In [ ]:
# Get the shape/size of numpy array

a.shape

(5,)

In [ ]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [ ]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [ ]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [ ]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [ ]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [ ]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

### **Numpy Array Operations**

In [ ]:
# Power of Numpy
x = np.arange(5)
y = np.arange(5)
print(x)
print(y)
print(x + y)
print(x * y)
print(x ** y)

[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4 6 8]
[ 0  1  4  9 16]
[  1   1   4  27 256]


In [ ]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [ ]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [ ]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [ ]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [ ]:
x = np.arange(12)
c = x.reshape(4,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## **Numpy to Load and Save Files**

In [ ]:
!wget https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

--2022-07-27 15:32:40--  https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv
Resolving web.stanford.edu (web.stanford.edu)... 171.67.215.200, 2607:f6d0:0:925a::ab43:d7c8
Connecting to web.stanford.edu (web.stanford.edu)|171.67.215.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44225 (43K) [text/csv]
Saving to: ‘titanic.csv’

titanic.csv         100%[===================>]  43.19K  --.-KB/s    in 0.08s   

2022-07-27 15:32:40 (534 KB/s) - ‘titanic.csv’ saved [44225/44225]



In [ ]:
a = np.array(['apple','banana','Cherries']) # numpy list

#np.save("new_array",x)
#np.load("new_array.npy")

np.savetxt('fruits.txt',c) # saving the list

In [ ]:
data = np.genfromtxt('titanic.csv',delimiter=',')

In [ ]:
data.shape

(888, 8)

# **Exercise** Numpy

In [4]:
# Given an integer array of size 10. Print the index of elements which are multiple of 3. 
import numpy as np

a = np.array([1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
'''for i in a:
    if i%3==0:
        print(i)
'''
a[a%3==0]

array([ 3,  9, 15])

In [13]:
# Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[(a>=3) & (a<=8)]

array([3, 4, 5, 6, 7, 8])

In [21]:
# Given a 1D array, sort the values

a = np.array( [[21,20,19, 18, 17],
  [16, 15, 14, 13, 12],
  [11, 10,  9,  8,  7],
  [ 6,  5,  4,  3 , 2]])


Sort the Given Array in to this 2D Format

```
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]
```

In [22]:
a.sort(axis=0)
a

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [69]:
# Given an integer array of size 9 and replace the first occurrence of maximum value by 0?

a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
a

array([11,  2, 13,  4, 15,  6, 27,  8, 19])

In [79]:
a[a.argmax()]=9
a

array([11,  2, 13,  4, 15,  6,  9,  8,  9])

In [82]:
# Create an integer Identity matrix (5, 6) using Numpy function
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])