In [2]:
import numpy as np

In [3]:
a1= np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a2= np.array(['a','e','i','o','u'])
a2

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [5]:
a3= np.ones(10,dtype= 'int64').reshape(2,5)
a3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [6]:
a4 = np.array([2.7,-2,-19.0,3.4,99.9,10.6, 0,13])
a4_1 = np.resize(a, (3,3))
print(a4)
print(a4_1)
print("Dimention : ",a4_1.ndim)

NameError: name 'a' is not defined

In [7]:
a5 = np.arange(4,62,4, dtype='float32').reshape(3,5)
a5

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]], dtype=float32)

In [8]:
b2 = a3.reshape(-1)
b2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [9]:
b3= a2[1:3]
b3

array(['e', 'i'], dtype='<U1')

In [10]:
b4 = myarray1[1:,0:]
b4

NameError: name 'myarray1' is not defined

In [11]:
b5 = myarray1[0:,0:2]
b5

NameError: name 'myarray1' is not defined

In [12]:
b6 = myarray1[1:,0:1]
b6

NameError: name 'myarray1' is not defined

In [13]:
b7 =a2[::-1] 
b7

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [14]:
b7 =np.flipud(a2)
b7

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [15]:
np.tile(a2,4)

array(['a', 'e', 'i', 'o', 'u', 'a', 'e', 'i', 'o', 'u', 'a', 'e', 'i',
       'o', 'u', 'a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [16]:
c1= a3//3
c1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [17]:
c2= np.array([1,2,3,4,5])
c_2 = np.array([3,4,5,8,9])

cc= c2+c_2
cc


array([ 4,  6,  8, 12, 14])

In [18]:
c3 = c2-c_2
c3

array([-2, -2, -2, -4, -4])

In [19]:
c4 =  c2*c_2
c4

array([ 3,  8, 15, 32, 45])

In [20]:
c6= c2/c_2
c6

array([0.33333333, 0.5       , 0.6       , 0.5       , 0.55555556])

In [21]:
print(c2)
c7 = (c2*3)
print(c7)
print(c7/2)

[1 2 3 4 5]
[ 3  6  9 12 15]
[1.5 3.  4.5 6.  7.5]


In [22]:
d1= a3.transpose()
d1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [23]:
d3 =np.sort(a4_1,axis = 1)
d3

NameError: name 'a4_1' is not defined

In [24]:
a5

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]], dtype=float32)

In [25]:
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E = np.split(a5,5,axis = 1)
print(myarray2A)
print(myarray2B)
print(myarray2C)
print(myarray2D)
print(myarray2E)


[[ 4.]
 [24.]
 [44.]]
[[ 8.]
 [28.]
 [48.]]
[[12.]
 [32.]
 [52.]]
[[16.]
 [36.]
 [56.]]
[[20.]
 [40.]
 [60.]]


In [29]:
zerosA,zerosB,zerosC,zerosD,e= np.split(a1,[2,5,7,8])
print(zerosA)

[0. 0.]


In [173]:
n = int(input("please give a number : "))

reverse = 0
while n!=0:
    reverse = reverse*10 + n%10 #0+7=7  #70+6=76
    print(reverse)
    n = (n//10) #56 #5 
    print(n,"\n")
# print("After reverse :",reverse)

please give a number : 567
7
56 

76
5 

765
0 



enter number: 234
4
23
43
2
432
0
output =  432


In [178]:
import pandas as pd


In [181]:
a =pd.Series([4,4,4,3,6,5,65])
a

0     4
1     4
2     4
3     3
4     6
5     5
6    65
dtype: int64

In [182]:
a.nsmallest()

3    3
0    4
1    4
2    4
5    5
dtype: int64

In [183]:
a.nlargest()

6    65
4     6
5     5
0     4
1     4
dtype: int64

In [184]:
a.sort_values()

3     3
0     4
1     4
2     4
5     5
4     6
6    65
dtype: int64

In [4]:
import sklearn

In [5]:
sklearn.__version__

'1.0.2'

In [4]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [6]:
import seaborn
seaborn.__version__

'0.11.2'